name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/serviciocliente-api:latest ./ClienteAPI

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/serviciocliente-api:latest
