name: Build Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/serviciocliente-api:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/serviciocliente-api:latest
